// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PD4ld-fH3w16JLKlr7VgeHrDEJYV8SY',
    appId: '1:850281785375:web:8c1296b0c8fc06da488d2a',
    messagingSenderId: '850281785375',
    projectId: 'flybox-377d6',
    authDomain: 'flybox-377d6.firebaseapp.com',
    storageBucket: 'flybox-377d6.firebasestorage.app',
    measurementId: 'G-954H7JRGVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7v9EMZuuILCLyVcAAwNkDvFcHpaStiz8',
    appId: '1:850281785375:android:268da7937be9e0c9488d2a',
    messagingSenderId: '850281785375',
    projectId: 'flybox-377d6',
    storageBucket: 'flybox-377d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVfIAu9QfiL_xy737FyXmChJfFAJbWvU',
    appId: '1:850281785375:ios:0ec08a5aceaa2ab4488d2a',
    messagingSenderId: '850281785375',
    projectId: 'flybox-377d6',
    storageBucket: 'flybox-377d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVfIAu9QfiL_xy737FyXmChJfFAJbWvU',
    appId: '1:850281785375:ios:0ec08a5aceaa2ab4488d2a',
    messagingSenderId: '850281785375',
    projectId: 'flybox-377d6',
    storageBucket: 'flybox-377d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1PD4ld-fH3w16JLKlr7VgeHrDEJYV8SY',
    appId: '1:850281785375:web:07e67c0c4bd8af25488d2a',
    messagingSenderId: '850281785375',
    projectId: 'flybox-377d6',
    authDomain: 'flybox-377d6.firebaseapp.com',
    storageBucket: 'flybox-377d6.firebasestorage.app',
    measurementId: 'G-BYH6J5K3M9',
  );
}
